name: Paths filter test
on:
  push:
    branches:
      "feature/sample_training"

jobs:
  paths-filter:
    runs-on: [self-hosted, theia]
    outputs:
      output1: ${{ steps.filter.outputs.readme }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: check what's in the directory
      run: |
        ls
        
    - name: Filter README  
      uses: dorny/paths-filter@v2.10.1
      id: filter
      with:
        filters: |
          readme:
            - 'README.md'
    # run only if 'workflows' files were changed
    - name: readme tests
      if: steps.filter.outputs.readme == 'true'
      run: echo "readme file changed due to improved training"

    # run only if not 'workflows' files were changed
    - name: not readme tests
      if: steps.filter.outputs.readme != 'true'
      run: echo "readme file NOT changed due to improved training"